### ISSUE TITLE
geary is not showing on the menu.

### ISSUE THREAD

**Issue by ghost** [screenfreeze/messagingmenu#40]
hi, 

appreciate your time maintaining and developing this extension its a very useful extension, i just wanted to bring to your attention the fact that the messaging menu is not showing geary as one of the options, i briefly looked at the code and everything seems to be ok so im puzzled as to what the reason may be as im currently not using a gnome desktop i am unable to investigate further, it would be nice if you could find a fix to this issue when you have some spare time.

kind regards
##
this issue was replicated on the following system setups.

**system details**

ubuntu gnome = 16.04 & 17.10

Arch = latest

gnome-shell = 3.18 >+ 3.26

**installed via gnome extensions**

Logs from the systemd journal = no logs

**Comment by sinisterstuf** [comment]
Hi, these days people are renaming the desktop entries for their apps to add the fully qualified name, so e.g. `geary` has become `org.gnome.Geary` and the messaging menu doesn't find it under the old name. Most "disappearing apps" issues are caused by this, thanks for reporting the issue, it should be fixed now in Version 14 of the extension! :+1:
