### ISSUE TITLE
Show mail/message counts

### ISSUE THREAD

**Issue by oae** [screenfreeze/messagingmenu#6]
Can you make this extension show mail counts for thunderbird and message counts for empathy? Also it would be good if it changes the icon when there is a new mail/message to notify us.

**Comment by gogi983** [comment]
Hello,

Is there any improvement on this suggestion since last comment? I was wondering if this kind of stuff would be available soon when I found this discussion.

**Comment by sinisterstuf** [comment]
Nope, no improvements. I'm not sure how @screenfreeze implemented this and to be honest it is not a feature that I use, so if someone needs it I would prefer to merge in a solution from pull request. Anyway I've put some logging around the code block that determines if there are unread messages, maybe there are precise numbers there, which could be used for notification counts. If that is true, then all we need is to display that number somehow.

**Comment by gogi983** [comment]
I saw what you"re saying about logging, unread messages and other stuff but I don"t know how this is implemented and how it should work exactly? Actually there seems to be a feature that changes icon color when new messages are incoming, but this does neither work for me.

**Comment by sinisterstuf** [comment]
Yes, I think this used to work with older versions of GNOME Shell, so it could be that the method for checking notifications has changed in new versions. The main difficulty with this issue is that, as far as I know, the notifications are implemented by the apps, not by GNOME, so it's up to the individual app developers whether we can support their program and count the notifications.
